### ISSUE TITLE
Reading initial conditions from Gadget

### ISSUE THREAD

**Issue by Lagrang3** [gevolution-code/gevolution-1.2#3]
Does `gevolution` support reading initial conditions from gadget snapshots?
The manual doesn't mention it. It would be nice to be able to.

I actually tried, with the following setting file:
```
IC generator = read from disk
particle file = /tmp/gadget/output/snapshot_000
...
```

where `snapshot_000` is some snapshot produced by Gadget4. 
However the LATfield output from that run warns that
```
...
all particles have their mass set to: 0
...
```
which is weird, because in the snapshot header is clearly written that particles have their mass set to `133.535`.

**Comment by gevolution-code** [comment]
Yes, reading Gadget2 binary snapshots as initial data is supported by _gevolution_ and you are using the correct procedure for that. The output from LATfield2 is spurious in this case, the reason being that the particle handler is initialised before the snapshot is being read, and hence the code does not yet know the particle mass (in the standard approach the mass is known because the number of particles is already determined before the particle handler is initialised). The mass is set to the correct value once the snapshot is read, but LATfield2 does not produce any output at that stage.

As a comment aside, the fact that LATfield2 produces standard output at all (except from error messages) is not a great feature, given that it is supposed to be a library.

**Comment by Lagrang3** [comment]
> As a comment aside, the fact that LATfield2 produces standard output at all (except from error messages) is not a great feature, given that it is supposed to be a library.

Good point! I guess we should provide some form of logging mechanism into LATfield to be retrieved on demand.
Even error messages should be avoided. As a C++ library LATfield should produce [exceptions](https://www.cplusplus.com/doc/tutorial/exceptions/) which is the de-facto way of handling errors in C++.
